import pg from 'pg';
import type { CollectionName } from './postgres.js';
import { FieldDef, RELATIONAL_TABLES, SqlType, TableDef } from './relationalSchema.js';

export { RELATIONAL_TABLE_NAMES, RELATIONAL_TABLES } from './relationalSchema.js';

function sqlType(type: SqlType): string {
  switch (type) {
    case 'boolean':
      return 'BOOLEAN';
    case 'integer':
      return 'INTEGER';
    case 'numeric':
      return 'NUMERIC';
    case 'timestamptz':
      return 'TIMESTAMPTZ';
    case 'text[]':
      return 'TEXT[]';
    case 'jsonb':
      return 'JSONB';
    default:
      return 'TEXT';
  }
}

function getPath(source: Record<string, unknown>, path: string): unknown {
  const parts = path.split('.');
  let current: unknown = source;
  for (const part of parts) {
    if (current == null || typeof current !== 'object') return undefined;
    current = (current as Record<string, unknown>)[part];
  }
  return current;
}

function setPath(target: Record<string, unknown>, path: string, value: unknown): void {
  const parts = path.split('.');
  let current = target;
  for (let index = 0; index < parts.length - 1; index += 1) {
    const part = parts[index];
    const next = current[part];
    if (next == null || typeof next !== 'object' || Array.isArray(next)) {
      current[part] = {};
    }
    current = current[part] as Record<string, unknown>;
  }
  current[parts[parts.length - 1]] = value;
}

function iso(value: Date | string | null | undefined): string | undefined {
  if (!value) return undefined;
  return value instanceof Date ? value.toISOString() : String(value);
}

function toDbValue(value: unknown, type: SqlType): unknown {
  if (value == null || value === '') return null;
  switch (type) {
    case 'boolean':
      return Boolean(value);
    case 'integer':
      return Number.isFinite(Number(value)) ? Math.trunc(Number(value)) : null;
    case 'numeric':
      return Number.isFinite(Number(value)) ? Number(value) : null;
    case 'timestamptz':
      return iso(value as Date | string) || null;
    case 'text[]':
      return Array.isArray(value) ? value.map((item) => String(item)) : null;
    case 'jsonb':
      return JSON.stringify(value);
    default:
      return String(value);
  }
}

function fromDbValue(value: unknown, type: SqlType): unknown {
  if (value == null) return undefined;
  switch (type) {
    case 'boolean':
      return Boolean(value);
    case 'integer':
      return Number(value);
    case 'numeric':
      return Number(value);
    case 'timestamptz':
      return iso(value as Date | string);
    case 'text[]':
      return Array.isArray(value) ? value : [];
    case 'jsonb':
      return typeof value === 'string' ? JSON.parse(value) : value;
    default:
      return String(value);
  }
}

export function buildCreateTableSql(def: TableDef): string {
  const columns = def.fields
    .map((field) => `  ${field.column} ${sqlType(field.type)}`)
    .join(',\n');
  return `
CREATE TABLE IF NOT EXISTS ${def.table} (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  record_key TEXT NOT NULL UNIQUE,
${columns}
);
`;
}

export const RELATIONAL_TABLES_DDL = RELATIONAL_TABLES.map(buildCreateTableSql).join('\n');

export function addMissingColumnSql(def: TableDef): string {
  return def.fields
    .map((field) => `ALTER TABLE ${def.table} ADD COLUMN IF NOT EXISTS ${field.column} ${sqlType(field.type)};`)
    .join('\n');
}

function rowToRecord(def: TableDef, row: Record<string, unknown>): Record<string, unknown> {
  const record: Record<string, unknown> = {
    id: String(row.record_key || ''),
  };
  for (const field of def.fields) {
    const value = fromDbValue(row[field.column], field.type);
    if (value === undefined) continue;
    setPath(record, field.key, value);
  }
  return record;
}

function recordValues(def: TableDef, record: Record<string, unknown>): unknown[] {
  return [
    String(record.id || ''),
    ...def.fields.map((field) => toDbValue(getPath(record, field.key), field.type)),
  ];
}

function insertSql(def: TableDef): string {
  const columns = ['record_key', ...def.fields.map((field) => field.column)];
  const params = columns.map((_, index) => {
    const field: FieldDef | undefined = index === 0 ? undefined : def.fields[index - 1];
    const placeholder = `$${index + 1}`;
    if (field?.type === 'timestamptz') return `${placeholder}::timestamptz`;
    if (field?.type === 'jsonb') return `${placeholder}::jsonb`;
    if (field?.type === 'text[]') return `${placeholder}::text[]`;
    return placeholder;
  });
  const updates = def.fields.map((field) => `${field.column} = EXCLUDED.${field.column}`).join(',\n            ');
  return `
          INSERT INTO ${def.table} (${columns.join(', ')})
          VALUES (${params.join(', ')})
          ON CONFLICT (record_key) DO UPDATE SET
            ${updates}
  `;
}

export async function loadRelationalCollections(
  client: pg.Pool | pg.PoolClient
): Promise<Partial<Record<CollectionName, unknown[]>>> {
  const out: Partial<Record<CollectionName, unknown[]>> = {};
  for (const def of RELATIONAL_TABLES) {
    const result = await client.query<Record<string, unknown>>(`SELECT * FROM ${def.table} ORDER BY id ASC`);
    out[def.collection] = result.rows.map((row) => rowToRecord(def, row));
  }
  return out;
}

export async function saveRelationalCollections(
  client: pg.PoolClient,
  collections: Partial<Record<CollectionName, unknown[]>>,
  only?: CollectionName[]
): Promise<void> {
  const selected = only ? new Set(only) : null;
  for (const def of RELATIONAL_TABLES) {
    if (selected && !selected.has(def.collection)) continue;
    const records = ((collections[def.collection] as Record<string, unknown>[] | undefined) ?? []).filter(
      (record) => record && record.id
    );
    const keepKeys = records.map((record) => String(record.id));
    if (!keepKeys.length) {
      await client.query(`DELETE FROM ${def.table}`);
      continue;
    }
    await client.query(`DELETE FROM ${def.table} WHERE NOT (record_key = ANY($1::text[]))`, [keepKeys]);
    const sql = insertSql(def);
    for (const record of records) {
      await client.query(sql, recordValues(def, record));
    }
  }
}

export async function migrateJsonCollectionsIfNeeded(
  client: pg.PoolClient,
  jsonCollections: Partial<Record<CollectionName, unknown[]>>
): Promise<boolean> {
  let migrated = false;
  for (const def of RELATIONAL_TABLES) {
    const count = await client.query<{ count: string }>(`SELECT COUNT(*)::text AS count FROM ${def.table}`);
    const existing = Number(count.rows[0]?.count || 0);
    const incoming = jsonCollections[def.collection] ?? [];
    if (existing > 0 || incoming.length === 0) continue;
    const sql = insertSql(def);
    for (const record of incoming as Record<string, unknown>[]) {
      if (!record?.id) continue;
      await client.query(sql, recordValues(def, record));
      migrated = true;
    }
  }
  return migrated;
}
