import { NotificationPreferences, User } from '../types.js';
import { getPool } from './postgres.js';

export const USERS_TABLE_DDL = `
CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_key TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  phone TEXT,
  role TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  employee_id TEXT,
  role_id TEXT,
  role_code TEXT,
  team_id TEXT,
  team_name TEXT,
  team_lead_id TEXT,
  team_lead_name TEXT,
  reporting_manager_id TEXT,
  reporting_manager_name TEXT,
  account_status TEXT,
  password_hash TEXT,
  password_created_at TIMESTAMPTZ,
  email_verified BOOLEAN NOT NULL DEFAULT FALSE,
  email_verification_token_hash TEXT,
  email_verification_expires_at TIMESTAMPTZ,
  invitation_code_hash TEXT,
  invitation_expires_at TIMESTAMPTZ,
  invitation_used_at TIMESTAMPTZ,
  invitation_created_at TIMESTAMPTZ,
  password_reset_token_hash TEXT,
  password_reset_expires_at TIMESTAMPTZ,
  password_reset_used_at TIMESTAMPTZ,
  password_changed_at TIMESTAMPTZ,
  pref_email_enabled BOOLEAN,
  pref_in_app_enabled BOOLEAN,
  pref_assignment BOOLEAN,
  pref_forward BOOLEAN,
  pref_reminder BOOLEAN,
  pref_approval BOOLEAN,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE VIEW user_directory AS
SELECT
  id,
  name,
  email,
  COALESCE(NULLIF(phone, ''), '—') AS phone,
  role,
  status,
  created_at
FROM users
ORDER BY id;
`;

type UserRow = {
  id: number;
  user_key: string;
  name: string;
  email: string;
  phone: string | null;
  role: string;
  status: User['status'];
  created_at: Date | string;
  employee_id: string | null;
  role_id: string | null;
  role_code: string | null;
  team_id: string | null;
  team_name: string | null;
  team_lead_id: string | null;
  team_lead_name: string | null;
  reporting_manager_id: string | null;
  reporting_manager_name: string | null;
  account_status: User['account_status'] | null;
  password_hash: string | null;
  password_created_at: Date | string | null;
  email_verified: boolean | null;
  email_verification_token_hash: string | null;
  email_verification_expires_at: Date | string | null;
  invitation_code_hash: string | null;
  invitation_expires_at: Date | string | null;
  invitation_used_at: Date | string | null;
  invitation_created_at: Date | string | null;
  password_reset_token_hash: string | null;
  password_reset_expires_at: Date | string | null;
  password_reset_used_at: Date | string | null;
  password_changed_at: Date | string | null;
  pref_email_enabled: boolean | null;
  pref_in_app_enabled: boolean | null;
  pref_assignment: boolean | null;
  pref_forward: boolean | null;
  pref_reminder: boolean | null;
  pref_approval: boolean | null;
  updated_at: Date | string | null;
};

function iso(value: Date | string | null | undefined): string | undefined {
  if (!value) return undefined;
  return value instanceof Date ? value.toISOString() : value;
}

function requiredIso(value: Date | string | null | undefined, fallback: string): string {
  return iso(value) || fallback;
}

function text(value: string | null | undefined): string | undefined {
  const next = (value || '').trim();
  return next || undefined;
}

function rowToUser(row: UserRow): User {
  const createdAt = requiredIso(row.created_at, new Date().toISOString());
  const prefs: NotificationPreferences | undefined =
    row.pref_email_enabled == null &&
    row.pref_in_app_enabled == null &&
    row.pref_assignment == null &&
    row.pref_forward == null &&
    row.pref_reminder == null &&
    row.pref_approval == null
      ? undefined
      : {
          email_enabled: Boolean(row.pref_email_enabled),
          in_app_enabled: Boolean(row.pref_in_app_enabled),
          assignment: Boolean(row.pref_assignment),
          forward: Boolean(row.pref_forward),
          reminder: Boolean(row.pref_reminder),
          approval: Boolean(row.pref_approval),
        };

  const user: User = {
    id: row.user_key,
    employee_id: row.employee_id || '',
    name: row.name,
    email: row.email,
    phone: row.phone || '',
    role_id: row.role_id || '',
    role_code: row.role_code || '',
    role_name: row.role,
    status: row.status === 'INACTIVE' ? 'INACTIVE' : 'ACTIVE',
    created_at: createdAt,
    updated_at: requiredIso(row.updated_at, createdAt),
  };

  if (text(row.team_id)) user.team_id = row.team_id!;
  if (text(row.team_name)) user.team_name = row.team_name!;
  if (text(row.team_lead_id)) user.team_lead_id = row.team_lead_id!;
  if (text(row.team_lead_name)) user.team_lead_name = row.team_lead_name!;
  if (text(row.reporting_manager_id)) user.reporting_manager_id = row.reporting_manager_id!;
  if (text(row.reporting_manager_name)) user.reporting_manager_name = row.reporting_manager_name!;
  if (row.account_status) user.account_status = row.account_status;
  if (row.password_hash) user.password_hash = row.password_hash;
  if (iso(row.password_created_at)) user.password_created_at = iso(row.password_created_at);
  if (row.email_verified != null) user.email_verified = row.email_verified;
  if (row.email_verification_token_hash) user.email_verification_token_hash = row.email_verification_token_hash;
  if (iso(row.email_verification_expires_at)) user.email_verification_expires_at = iso(row.email_verification_expires_at);
  if (row.invitation_code_hash) user.invitation_code_hash = row.invitation_code_hash;
  if (iso(row.invitation_expires_at)) user.invitation_expires_at = iso(row.invitation_expires_at);
  if (iso(row.invitation_used_at)) user.invitation_used_at = iso(row.invitation_used_at);
  if (iso(row.invitation_created_at)) user.invitation_created_at = iso(row.invitation_created_at);
  if (row.password_reset_token_hash) user.password_reset_token_hash = row.password_reset_token_hash;
  if (iso(row.password_reset_expires_at)) user.password_reset_expires_at = iso(row.password_reset_expires_at);
  if (iso(row.password_reset_used_at)) user.password_reset_used_at = iso(row.password_reset_used_at);
  if (iso(row.password_changed_at)) user.password_changed_at = iso(row.password_changed_at);
  if (prefs) user.notification_preferences = prefs;
  return user;
}

function userValues(user: User) {
  const prefs = user.notification_preferences;
  return [
    user.id,
    user.name,
    user.email.trim().toLowerCase(),
    text(user.phone) || null,
    user.role_name || user.role_code || 'Team Member',
    user.status === 'INACTIVE' ? 'INACTIVE' : 'ACTIVE',
    user.created_at,
    user.employee_id || null,
    user.role_id || null,
    user.role_code || null,
    user.team_id || null,
    user.team_name || null,
    user.team_lead_id || null,
    user.team_lead_name || null,
    user.reporting_manager_id || null,
    user.reporting_manager_name || null,
    user.account_status || null,
    user.password_hash || null,
    user.password_created_at || null,
    user.email_verified ?? false,
    user.email_verification_token_hash || null,
    user.email_verification_expires_at || null,
    user.invitation_code_hash || null,
    user.invitation_expires_at || null,
    user.invitation_used_at || null,
    user.invitation_created_at || null,
    user.password_reset_token_hash || null,
    user.password_reset_expires_at || null,
    user.password_reset_used_at || null,
    user.password_changed_at || null,
    prefs ? prefs.email_enabled : null,
    prefs ? prefs.in_app_enabled : null,
    prefs ? prefs.assignment : null,
    prefs ? prefs.forward : null,
    prefs ? prefs.reminder : null,
    prefs ? prefs.approval : null,
    user.updated_at || user.created_at,
  ];
}

export async function loadUsersTable(): Promise<User[]> {
  const result = await getPool().query<UserRow>(`SELECT * FROM users ORDER BY id ASC`);
  return result.rows.map(rowToUser);
}

export async function saveUsersTable(users: User[]): Promise<void> {
  const client = await getPool().connect();
  try {
    await client.query('BEGIN');
    const keepKeys = users.map((user) => user.id);
    if (!keepKeys.length) {
      await client.query('DELETE FROM users');
    } else {
      await client.query(`DELETE FROM users WHERE NOT (user_key = ANY($1::text[]))`, [keepKeys]);
    }

    for (const user of users) {
      await client.query(
        `
          INSERT INTO users (
            user_key, name, email, phone, role, status, created_at,
            employee_id, role_id, role_code, team_id, team_name, team_lead_id, team_lead_name,
            reporting_manager_id, reporting_manager_name, account_status, password_hash, password_created_at,
            email_verified, email_verification_token_hash, email_verification_expires_at,
            invitation_code_hash, invitation_expires_at, invitation_used_at, invitation_created_at,
            password_reset_token_hash, password_reset_expires_at, password_reset_used_at, password_changed_at,
            pref_email_enabled, pref_in_app_enabled, pref_assignment, pref_forward, pref_reminder, pref_approval,
            updated_at
          )
          VALUES (
            $1, $2, $3, $4, $5, $6, $7::timestamptz,
            $8, $9, $10, $11, $12, $13, $14,
            $15, $16, $17, $18, $19::timestamptz,
            $20, $21, $22::timestamptz,
            $23, $24::timestamptz, $25::timestamptz, $26::timestamptz,
            $27, $28::timestamptz, $29::timestamptz, $30::timestamptz,
            $31, $32, $33, $34, $35, $36,
            $37::timestamptz
          )
          ON CONFLICT (user_key) DO UPDATE SET
            name = EXCLUDED.name,
            email = EXCLUDED.email,
            phone = EXCLUDED.phone,
            role = EXCLUDED.role,
            status = EXCLUDED.status,
            created_at = EXCLUDED.created_at,
            employee_id = EXCLUDED.employee_id,
            role_id = EXCLUDED.role_id,
            role_code = EXCLUDED.role_code,
            team_id = EXCLUDED.team_id,
            team_name = EXCLUDED.team_name,
            team_lead_id = EXCLUDED.team_lead_id,
            team_lead_name = EXCLUDED.team_lead_name,
            reporting_manager_id = EXCLUDED.reporting_manager_id,
            reporting_manager_name = EXCLUDED.reporting_manager_name,
            account_status = EXCLUDED.account_status,
            password_hash = EXCLUDED.password_hash,
            password_created_at = EXCLUDED.password_created_at,
            email_verified = EXCLUDED.email_verified,
            email_verification_token_hash = EXCLUDED.email_verification_token_hash,
            email_verification_expires_at = EXCLUDED.email_verification_expires_at,
            invitation_code_hash = EXCLUDED.invitation_code_hash,
            invitation_expires_at = EXCLUDED.invitation_expires_at,
            invitation_used_at = EXCLUDED.invitation_used_at,
            invitation_created_at = EXCLUDED.invitation_created_at,
            password_reset_token_hash = EXCLUDED.password_reset_token_hash,
            password_reset_expires_at = EXCLUDED.password_reset_expires_at,
            password_reset_used_at = EXCLUDED.password_reset_used_at,
            password_changed_at = EXCLUDED.password_changed_at,
            pref_email_enabled = EXCLUDED.pref_email_enabled,
            pref_in_app_enabled = EXCLUDED.pref_in_app_enabled,
            pref_assignment = EXCLUDED.pref_assignment,
            pref_forward = EXCLUDED.pref_forward,
            pref_reminder = EXCLUDED.pref_reminder,
            pref_approval = EXCLUDED.pref_approval,
            updated_at = EXCLUDED.updated_at
        `,
        userValues(user)
      );
    }
    await client.query('COMMIT');
  } catch (error) {
    await client.query('ROLLBACK');
    throw error;
  } finally {
    client.release();
  }
}

export function formatUserDirectory(users: Array<Pick<User, 'name' | 'email' | 'phone' | 'role_name' | 'role_code' | 'status' | 'created_at'>>): string {
  const header = 'id | name | email | phone | role | status | created_at';
  const rows = users.map((user, index) =>
    [
      index + 1,
      user.name,
      user.email,
      user.phone?.trim() || '—',
      user.role_name || user.role_code,
      user.status,
      (user.created_at || '').slice(0, 10),
    ].join(' | ')
  );
  return [header, '', ...rows].join('\n');
}
